packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
allowBuilds:
  esbuild: true
  iframe-resizer: true
  lefthook: false
  nx: true
minimumReleaseAgeExclude:
  - '@commercelayer/sdk@8.0.2'
